#include: package:analyzer/analysis_options.yaml
import: 'package: analyzer/analysis_options.yaml'

# linter:
#   rules:
#     avoid_print: false  
#     prefer_const_constructors: false

# analyzer:
#   exclude:
#     - "**/*.g.dart"
#     - "**/*.freezed.dart"
#   errors:
#     invalid_annotation_target: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
